run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
