ALTER TABLE console_roles
    ADD COLUMN display_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN sort INTEGER NOT NULL DEFAULT 0;

ALTER TABLE console_admins
    MODIFY COLUMN email VARCHAR(160) NULL,
    ADD COLUMN real_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN display_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN avatar VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN last_login_ip VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN login_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN remark VARCHAR(500) NOT NULL DEFAULT '';
