ALTER TABLE console_roles
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS sort INTEGER NOT NULL DEFAULT 0;

ALTER TABLE console_admins
    ALTER COLUMN email DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(32) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS real_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS display_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS login_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS remark VARCHAR(500) NOT NULL DEFAULT '';

ALTER TABLE console_admins
    DROP CONSTRAINT IF EXISTS console_admins_email_key;

DROP INDEX IF EXISTS idx_console_admins_phone;

CREATE UNIQUE INDEX IF NOT EXISTS idx_console_admins_email_non_empty ON console_admins (email) WHERE email <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_console_admins_phone_non_empty ON console_admins (phone) WHERE phone <> '';
