package config

import (
	"fmt"
	"strings"
	"unicode/utf8"
)

// MinInitialRootPasswordLength is the minimum length accepted for a manually
// configured bootstrap password. Passwords generated by the CLI are longer
// and continue to satisfy this requirement.
const MinInitialRootPasswordLength = 16

// ValidateInitialRootPassword validates a password before it is used to
// bootstrap the first Console administrator. The actual password is never
// included in an error message.
func ValidateInitialRootPassword(password string) error {
	password = strings.TrimSpace(password)
	if password == "" {
		return fmt.Errorf("initial root password must not be empty")
	}
	if utf8.RuneCountInString(password) < MinInitialRootPasswordLength {
		return fmt.Errorf("initial root password must be at least %d characters", MinInitialRootPasswordLength)
	}

	switch strings.ToLower(password) {
	case "change-me", "changeme", "password", "replace-with-your-password":
		return fmt.Errorf("initial root password must not use a placeholder value")
	default:
		return nil
	}
}
